# Copyright (c) 2023 Cisco Systems, Inc. and its affiliates All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

# Removed --platform flag to support both AMD64 and ARM64 (Apple Silicon)
FROM nginx:1.27-alpine
COPY ./default.conf /etc/nginx/conf.d/
